### ISSUE TITLE
CHM format download does not display any text in the help topics

### ISSUE THREAD

**Issue by buttflattery** [blacksmoke26/Yii2-Manual-CHM#1]
is just downloaded the CHM format and tried to view and nothing shows up, I am using windows 10 
![image](https://user-images.githubusercontent.com/1536454/27837162-24cf15c4-60fc-11e7-966e-41cbb7fd0b70.png)

**Comment by blacksmoke26** [comment]
If you are using Windows XP SP2 or later and you are going to download the documentation in CHM format, you need to "unblock" the file after downloading it by right-clicking on it in Windows Explorer and selecting the "Properties" menu item, then clicking on the "Unblock" button (on Windows Vista this is within the "Security" options). Failure to unblock the documentation file may result in error messages including "Navigation to the webpage was canceled" due to Windows security restrictions.
